@Echo Off
Echo Unregistering GPProcessVendorDataFunctions.dll
set COMMONPROGRAMFILESLOCATION=%COMMONPROGRAMFILES%
IF NOT "%PROCESSOR_ARCHITECTURE%" == "x86" set COMMONPROGRAMFILESLOCATION=%COMMONPROGRAMFILES(x86)%
"%COMMONPROGRAMFILESLOCATION%\ArcGIS\bin\ESRIRegasm.exe" "%~dp0\GPProcessVendorDataFunctions.dll" /p:desktop /u